name: CI

on:
  push:
    branches:
      - master
      - "!dependabot/**"
  schedule:
    - cron: "0 */4 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: '5.38'
          install-modules: |
            Path::Tiny

      - name: Run updateBlockLists
        run: python updateBlockLists.py
        
      - name: Generate date and time
        run: echo "DATE=$(date '+%F %T')" >> $GITHUB_ENV
        
      - name: Commit filters
        uses: EndBug/add-and-commit@v9.1.1
        with:
          add: 'hosts'
          default_author: github_actor 
          message: 'Cập nhật bộ lọc: ${{ env.DATE }}'
          push: true
